/* Kleenest media service: resize/compress first, then upload; supports consumer + business media. */
(function(){'use strict';const M=window.KleenestMedia=window.KleenestMedia||{};const BUCKETS={avatar:'avatars',review:'review-photos',social:'social-media',location:'location-photos'};const LIMITS={avatar:{maxEdge:1200,maxBytes:5*1024*1024,quality:.82},review:{maxEdge:1800,maxBytes:8*1024*1024,quality:.80},social:{maxEdge:1800,maxBytes:10*1024*1024,quality:.80},location:{maxEdge:2400,maxBytes:12*1024*1024,quality:.82},vr360:{maxEdge:4096,maxBytes:20*1024*1024,quality:.84}};const client=()=>{const c=window.KleenestSupabase?.getClient?.();if(!c)throw new Error('Supabase client unavailable');return c};
function resize(file,purpose){return new Promise((resolve,reject)=>{const c=LIMITS[purpose]||LIMITS.review;if(!file||!/^image\/(jpeg|png|webp)$/i.test(file.type||''))return reject(new Error('Only JPG, PNG, or WebP images are supported.'));const r=new FileReader();r.onerror=()=>reject(r.error||new Error('Could not read image'));r.onload=()=>{const i=new Image();i.onerror=()=>reject(new Error('Invalid image'));i.onload=()=>{const s=Math.min(1,c.maxEdge/Math.max(i.naturalWidth,i.naturalHeight)),w=Math.max(1,Math.round(i.naturalWidth*s)),h=Math.max(1,Math.round(i.naturalHeight*s)),can=document.createElement('canvas');can.width=w;can.height=h;can.getContext('2d',{alpha:false}).drawImage(i,0,0,w,h);can.toBlob(b=>{if(!b)return reject(new Error('Image compression failed'));if(b.size>c.maxBytes)return reject(new Error('Image remains too large after compression. Choose a smaller image.'));resolve({blob:b,width:w,height:h,sizeBytes:b.size,mimeType:'image/jpeg'});},'image/jpeg',c.quality)};i.src=r.result};r.readAsDataURL(file)})}
async function upload(file,purpose,meta={}){const cooked=await resize(file,purpose==='vr360'?'vr360':purpose),s=await client().auth.getSession(),uid=s.data.session?.user?.id;if(!uid)throw new Error('Sign in required to upload media.');const bucket=purpose==='vr360'?BUCKETS.location:BUCKETS[purpose],scope=meta.businessId||meta.locationId||meta.reviewId||meta.postId||uid,path=`${scope}/${uid}/${crypto.randomUUID()}.jpg`,up=await client().storage.from(bucket).upload(path,cooked.blob,{contentType:cooked.mimeType,upsert:false,cacheControl:'31536000'});if(up.error)throw up.error;const u=client().storage.from(bucket).getPublicUrl(path);return {...cooked,bucket,path,url:u.data.publicUrl,mediaType:purpose==='vr360'?'vr360':purpose};}
M.prepareImage=resize;M.upload=upload;M.uploadAvatar=f=>upload(f,'avatar');M.uploadReviewPhoto=f=>upload(f,'review');M.uploadSocialPhoto=f=>upload(f,'social');M.uploadLocationPhoto=f=>upload(f,'location');M.uploadVr360=f=>upload(f,'vr360');
M.recordLocationPhoto=async(media,locationId,userId,caption='',sortOrder=0)=>{const {data,error}=await client().from('location_photos').insert({location_id:locationId,user_id:userId,storage_path:media.path,caption,media_type:media.mediaType||'photo',mime_type:media.mimeType,size_bytes:media.sizeBytes,width:media.width,height:media.height,sort_order:sortOrder}).select().single();if(error)throw error;return data};
M.recordReviewPhoto=async(media,reviewId,sortOrder=0)=>{const {data,error}=await client().from('review_photos').insert({review_id:reviewId,storage_path:media.path,mime_type:media.mimeType,size_bytes:media.sizeBytes,width:media.width,height:media.height,sort_order:sortOrder}).select().single();if(error)throw error;return data};
M.createSocialPost=async({content='',locationId=null,media=null})=>{const s=await client().auth.getSession(),uid=s.data.session?.user?.id;if(!uid)throw new Error('Sign in required.');const row={user_id:uid,location_id:locationId,content,media_url:media?.url||null,media_type:media?.mediaType||null,media_storage_path:media?.path||null,media_size_bytes:media?.sizeBytes||null,media_width:media?.width||null,media_height:media?.height||null},r=await client().from('social_posts').insert(row).select().single();if(r.error)throw r.error;return r.data};
})();
