/* Kleenest QR surface: business QR generation/customization + verified consumer scanning + single-use access. */
(function(){'use strict';
 const Q=window.KleenestQR=window.KleenestQR||{};
 const esc=v=>String(v??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));
 const call=(name,args)=>window.KleenestSupabase?.rpc?.(name,args||{});
 const base=()=>{const u=new URL(location.href);u.search='';u.hash='';return u.href;};
 const qrImage=(code,size='220x220')=>'https://api.qrserver.com/v1/create-qr-code/?size='+size+'&data='+encodeURIComponent(base()+'?checkin='+encodeURIComponent(code));
 Q.ensure=locationId=>call('ensure_location_qr',{p_location_id:locationId});
 Q.customize=(locationId,label,customization)=>call('set_location_qr_customization',{p_location_id:locationId,p_label:label,p_customization:customization||{}});
 Q.analytics=businessId=>call('business_qr_analytics',{p_business_id:businessId});
 Q.verify=async(code,lat,lng)=>call('verify_checkin',{p_qr_code:code,p_lat:lat??null,p_lng:lng??null});
 Q.resolve=async code=>call('resolve_custom_qr_action',{p_qr_code:code});
 Q.recordVisit=locationId=>call('record_location_visit',{p_location_id:locationId,p_context:{source:'qr'}});
 Q.createSingleUseOffer=(partnerProgramId,name,description,priceCents,quantity,expiresAt)=>call('business_create_single_use_access_offer',{p_partner_program_id:partnerProgramId,p_name:name,p_description:description,p_price_cents:priceCents,p_quantity:quantity,p_expires_at:expiresAt||null});
 Q.singleUseOffers=()=>call('get_single_use_access_offers',{});
 Q.purchaseSingleUse=offerId=>call('purchase_single_use_access',{p_offer_id:offerId});
 Q.redeemSingleUse=purchaseId=>call('redeem_single_use_access',{p_purchase_id:purchaseId});
 Q.qrImage=qrImage;
 function parse(raw){try{const u=new URL(raw,location.href);return u.searchParams.get('checkin')||u.searchParams.get('kleenest_qr')||raw;}catch{return String(raw||'').trim();}}
 async function position(){try{return await new Promise((resolve,reject)=>navigator.geolocation?.getCurrentPosition(p=>resolve(p.coords),reject,{enableHighAccuracy:true,timeout:6000,maximumAge:60000}));}catch(e){return null;}}
 async function execute(raw){const code=parse(raw);if(!code)throw Error('No Kleenest QR code was found.');const action=await Q.resolve(code);if(action?.error)throw Error(action.error.message||action.error);const a=action?.data||action;if(!a?.action_type)throw Error('This QR has no configured action.');const type=String(a.action_type).toLowerCase();const payload=a.action_payload||{};if(type==='checkin'){const pos=await position();const result=await Q.verify(code,pos?.latitude,pos?.longitude);const check=result?.check_in||result;const profile=result?.profile||null;window.dispatchEvent(new CustomEvent('kleenest:qr-checkin',{detail:{code,check,profile,action:a}}));return result;}if(type==='promotion'){const id=payload.promotion_id||payload.id;if(!id)throw Error('This promotion QR is missing its promotion.');const result=await window.KleenestRuntime.redeemPromotion(id,a.location_id||null);return result;}if(type==='url'){const url=payload.url;if(!url)throw Error('This QR has no destination.');const parsed=new URL(url,location.href);if(!/^https?:$/.test(parsed.protocol))throw Error('Unsafe QR destination.');location.href=parsed.href;return {navigated:true};}if(type==='info'||type==='menu'||type==='social'||type==='offer'||type==='contest'||type==='custom'){const url=payload.url||payload.destination||payload.href;if(url){const parsed=new URL(url,location.href);if(!/^https?:$/.test(parsed.protocol))throw Error('Unsafe QR destination.');location.href=parsed.href;return {navigated:true};}window.dispatchEvent(new CustomEvent('kleenest:qr-action',{detail:{action:a}}));return a;}throw Error('Unsupported Kleenest QR action: '+type);}
 async function handle(raw){try{const result=await execute(raw);if(result?.navigated)return result;alert('✓ '+(result?.message||'Kleenest action completed.'));return result;}catch(e){alert(e?.message||'That QR code is invalid, inactive, or its action could not be completed.');return null;}}
 Q.execute=execute;
 Q.scan=async()=>{const user=window.KleenestRuntime?.user||await window.KleenestSupabase?.profile?.();if(!user){alert('Please sign in to scan a Kleenest QR.');return;}if(!navigator.mediaDevices?.getUserMedia){const code=prompt('Enter the Kleenest QR code:');if(code)await handle(code);return;}if(!('BarcodeDetector' in window)){const code=prompt('QR camera scanning is not supported by this browser. Enter the Kleenest QR code:');if(code)await handle(code);return;}const modal=document.createElement('div');modal.className='qr-scan-modal';modal.innerHTML='<div class="qr-scan-panel"><button class="ghost qr-scan-close" type="button">Close</button><h2>📷 Scan Kleenest QR</h2><p class="muted">Point the camera at a Kleenest QR code.</p><div class="qr-scan-frame"><video autoplay playsinline muted></video></div><p class="muted qr-scan-status">Scanning…</p></div>';document.body.appendChild(modal);const video=modal.querySelector('video');let stream=null,stopped=false,busy=false;const close=()=>{stopped=true;if(stream)stream.getTracks().forEach(t=>t.stop());modal.remove();};modal.querySelector('.qr-scan-close').onclick=close;try{stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'}}});video.srcObject=stream;await video.play();const detector=new BarcodeDetector({formats:['qr_code']});const loop=async()=>{if(stopped)return;if(!busy){try{const codes=await detector.detect(video);if(codes.length){busy=true;modal.querySelector('.qr-scan-status').textContent='QR recognized — completing action…';const result=await execute(codes[0].rawValue);if(result?.navigated)return;if(!stopped){modal.querySelector('.qr-scan-status').textContent='Complete ✓';setTimeout(close,500);}return;}}catch(e){busy=false;modal.querySelector('.qr-scan-status').textContent=e?.message||'QR action failed — try again.';setTimeout(()=>{if(!stopped)modal.querySelector('.qr-scan-status').textContent='Scanning…';},1800);}}requestAnimationFrame(loop);};loop();}catch(e){close();const code=prompt('Camera unavailable. Enter the Kleenest QR code:');if(code)await handle(code);}};
 Q.businessCard=async(location)=>{if(!location?.id)return '';try{const qr=await Q.ensure(location.id);const code=qr?.code;if(!code)return '';const canCustomize=['growth','enterprise'].includes(String(window.KleenestRuntime?.user?.businessTier||'').toLowerCase())||window.KleenestRuntime?.user?.isAdmin;return `<div class="card qr-business-card"><div class="qr-business-inner"><img src="${qrImage(code,'220x220')}" alt="Kleenest QR"><div><span class="badge verified">QR CHECK-IN</span><h3>${esc(qr.label||'Scan to Check In')}</h3><p class="muted">Every business location gets a working QR. Scans create verified visits, points, streaks, contests and business analytics.</p><p class="muted"><strong>Code:</strong> ${esc(code)}</p><div class="actions"><button class="secondary" data-qr-open="${esc(code)}">Open QR</button><button class="ghost" data-qr-print="${esc(code)}">Print</button>${canCustomize?`<button class="ghost" data-qr-customize="${esc(location.id)}">Customize</button>`:''}</div></div></div></div>`;}catch(e){return `<div class="card blue"><h3>QR check-in</h3><p class="muted">QR setup is temporarily unavailable. Refresh the business workspace and try again.</p></div>`;}};
 Q.bind=function(root){if(!root)return;root.querySelectorAll('[data-qr-open]').forEach(b=>b.onclick=()=>window.open(qrImage(b.dataset.qrOpen,'500x500'),'_blank'));root.querySelectorAll('[data-qr-print]').forEach(b=>b.onclick=()=>{const w=window.open('','_blank');if(!w)return;w.document.write(`<html><body style="font-family:system-ui;text-align:center;padding:30px"><h1>Kleenest</h1><img src="${qrImage(b.dataset.qrPrint,'500x500')}" style="width:400px;height:400px"><h2>Scan to Check In</h2><p>Check in, earn points and help improve this location.</p><button onclick="window.print()">Print</button></body></html>`);w.document.close();});root.querySelectorAll('[data-qr-customize]').forEach(b=>b.onclick=async()=>{const label=prompt('QR label:','Scan to Check In');if(label==null)return;const color=prompt('QR accent color name (optional):','teal');try{await Q.customize(b.dataset.qrCustomize,label,{accent:color||'teal'});alert('QR customization saved.');window.KleenestBusinessWorkspace?.load?.();window.dispatchEvent(new CustomEvent('kleenest:business-refresh'));}catch(e){alert(e?.message||'QR customization failed.');}});root.querySelectorAll('[data-scan-qr]').forEach(b=>b.onclick=Q.scan);};
 window.addEventListener('kleenest:qr-checkin',e=>{const p=e.detail?.profile;if(p&&window.KleenestRuntime){window.KleenestRuntime.user={...(window.KleenestRuntime.user||{}),points:p.points,level:p.level,streak:p.streak,totalCheckIns:p.total_check_ins,totalReviews:p.total_reviews};}window.dispatchEvent(new CustomEvent('kleenest:auth-state-changed'));});
})();
(function(){const load=()=>{if(document.querySelector('script[data-kleenest-advanced-controls]'))return;const s=document.createElement('script');s.src='kleenest-business-advanced-controls.js';s.dataset.kleenestAdvancedControls='1';document.head.appendChild(s);};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',load);else load();setTimeout(load,500);})();