/* Kleenest QR surface: business QR generation/customization + verified consumer scanning + action envelope. */
(function(){'use strict';
 const Q=window.KleenestQR=window.KleenestQR||{};
 const esc=v=>String(v??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));
 const call=(name,args)=>window.KleenestSupabase?.rpc?.(name,args||{});
 const base=()=>{const u=new URL(location.href);u.search='';u.hash='';return u.href;};
 const envelope=code=>JSON.stringify({k:'KLEENEST',v:1,id:String(code)});
 const qrImage=(code,size='220x220')=>'https://api.qrserver.com/v1/create-qr-code/?size='+size+'&data='+encodeURIComponent(envelope(code));
 Q.ensure=locationId=>call('ensure_location_qr',{p_location_id:locationId});
 Q.customize=(locationId,label,customization)=>call('set_location_qr_customization',{p_location_id:locationId,p_label:label,p_customization:customization||{}});
 Q.analytics=businessId=>call('business_qr_analytics',{p_business_id:businessId});
 Q.verify=async(code,lat,lng)=>call('verify_checkin',{p_qr_code:code,p_lat:lat??null,p_lng:lng??null});
 Q.resolve=async code=>call('resolve_custom_qr_action',{p_qr_code:code});
 function parse(raw){try{const text=String(raw||'').trim();try{const obj=JSON.parse(text);if(obj?.k==='KLEENEST'&&obj?.id)return String(obj.id);}catch{}const u=new URL(text,location.href);return u.searchParams.get('checkin')||u.searchParams.get('kleenest_qr')||u.searchParams.get('id')||text;}catch{return String(raw||'').trim();}}
 async function position(){try{return await new Promise((resolve,reject)=>navigator.geolocation?.getCurrentPosition(p=>resolve(p.coords),reject,{enableHighAccuracy:true,timeout:6000,maximumAge:60000}));}catch(e){return null;}}
 async function execute(raw){const code=parse(raw);if(!code)throw Error('No Kleenest QR code was found.');const action=await Q.resolve(code);if(action?.error)throw Error(action.error.message||action.error);const a=action?.data||action;if(!a?.action_type)throw Error('This QR has no configured action.');const type=String(a.action_type).toLowerCase();const payload=a.action_payload||{};if(type==='checkin'){const pos=await position();const result=await Q.verify(code,pos?.latitude,pos?.longitude);window.dispatchEvent(new CustomEvent('kleenest:qr-checkin',{detail:{code,check:result?.check_in||result,profile:result?.profile||null,action:a}}));return result;}if(type==='promotion'){const id=payload.promotion_id||payload.id;if(!id)throw Error('This promotion QR is missing its promotion.');return await window.KleenestRuntime.redeemPromotion(id,a.location_id||null);}if(type==='url'||['info','menu','social','offer','contest','custom'].includes(type)){const url=payload.url||payload.destination||payload.href;if(url){const parsed=new URL(url,location.href);if(!/^https?:$/.test(parsed.protocol))throw Error('Unsafe QR destination.');location.href=parsed.href;return {navigated:true};}window.dispatchEvent(new CustomEvent('kleenest:qr-action',{detail:{action:a}}));return a;}throw Error('Unsupported Kleenest QR action: '+type);}
 Q.execute=execute;
 Q.scan=async()=>{const user=window.KleenestRuntime?.user||await window.KleenestSupabase?.profile?.();if(!user){alert('Please sign in to scan a Kleenest QR.');return;}if(!navigator.mediaDevices?.getUserMedia||!('BarcodeDetector' in window)){const code=prompt('QR camera scanning is unavailable in this browser. Enter the Kleenest QR code:');if(code)await execute(code);return;}const modal=document.createElement('div');modal.className='qr-scan-modal';modal.innerHTML='<div class="qr-scan-panel"><button class="ghost qr-scan-close" type="button">×</button><h2>Scan Kleenest QR</h2><p class="muted">Point your camera at the code. It will run automatically.</p><div class="qr-scan-frame"><video autoplay playsinline muted></video></div><p class="muted qr-scan-status">Scanning…</p></div>';document.body.appendChild(modal);const video=modal.querySelector('video');let stream=null,stopped=false,busy=false;const close=()=>{stopped=true;if(stream)stream.getTracks().forEach(t=>t.stop());modal.remove();};modal.querySelector('.qr-scan-close').onclick=close;try{stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'}}});video.srcObject=stream;await video.play();const detector=new BarcodeDetector({formats:['qr_code']});const loop=async()=>{if(stopped)return;if(!busy){try{const codes=await detector.detect(video);if(codes.length){busy=true;modal.querySelector('.qr-scan-status').textContent='Recognized — completing…';try{const result=await execute(codes[0].rawValue);if(result?.navigated)return;modal.querySelector('.qr-scan-status').textContent='Complete ✓';setTimeout(close,450);}catch(e){busy=false;modal.querySelector('.qr-scan-status').textContent=e?.message||'Could not complete this QR action.';setTimeout(()=>{if(!stopped)modal.querySelector('.qr-scan-status').textContent='Scanning…';},1800);}}}catch(e){}}requestAnimationFrame(loop);};loop();}catch(e){close();alert(e?.message||'Camera access was unavailable.');}};
 Q.qrImage=qrImage;
 Q.businessCard=async(location)=>{if(!location?.id)return '';try{const qr=await Q.ensure(location.id);const code=qr?.code;if(!code)return '';const canCustomize=['growth','enterprise'].includes(String(window.KleenestRuntime?.user?.businessTier||'').toLowerCase())||window.KleenestRuntime?.user?.isAdmin;return `<div class="card qr-business-card"><div class="qr-business-inner"><img src="${qrImage(code,'220x220')}" alt="Kleenest QR"><div><span class="badge verified">QR CHECK-IN</span><h3>${esc(qr.label||'Scan to Check In')}</h3><p class="muted">Every business location gets a working QR. Scans create verified visits, points, streaks, contests and business analytics.</p><p class="muted"><strong>Code:</strong> ${esc(code)}</p><div class="actions"><button class="secondary" data-qr-open="${esc(code)}">Open QR</button><button class="ghost" data-qr-print="${esc(code)}">Print</button>${canCustomize?`<button class="ghost" data-qr-customize="${esc(location.id)}">Customize</button>`:''}</div></div></div></div>`;}catch(e){return '<div class="card blue"><h3>QR check-in</h3><p class="muted">QR setup is temporarily unavailable.</p></div>';}};
 Q.bind=function(root){if(!root)return;root.querySelectorAll('[data-qr-open]').forEach(b=>b.onclick=()=>window.open(qrImage(b.dataset.qrOpen,'500x500'),'_blank'));root.querySelectorAll('[data-scan-qr]').forEach(b=>b.onclick=Q.scan);};
 window.addEventListener('kleenest:qr-checkin',e=>{const p=e.detail?.profile;if(p&&window.KleenestRuntime)window.KleenestRuntime.user={...(window.KleenestRuntime.user||{}),points:p.points,level:p.level,streak:p.streak,totalCheckIns:p.total_check_ins,totalReviews:p.total_reviews};window.dispatchEvent(new CustomEvent('kleenest:auth-state-changed'));});
})();