/* Kleenest media service. Resizes before upload and records durable media metadata. */
(function(){'use strict';
 const M=window.KleenestMedia=window.KleenestMedia||{};
 const BUCKETS={avatar:'avatars',review:'review-photos',social:'social-media',location:'location-photos'};
 const LIMITS={avatar:{maxEdge:1200,maxBytes:5*1024*1024,quality:.82},review:{maxEdge:1800,maxBytes:8*1024*1024,quality:.80},social:{maxEdge:1800,maxBytes:10*1024*1024,quality:.80},location:{maxEdge:2400,maxBytes:12*1024*1024,quality:.82},vr360:{maxEdge:4096,maxBytes:12*1024*1024,quality:.84}};
 function client(){const c=window.KleenestSupabase?.getClient?.();if(!c)throw new Error('Supabase client unavailable');return c;}
 function ext(){return 'jpg';}
 function resize(file,purpose){return new Promise((resolve,reject)=>{const cfg=LIMITS[purpose]||LIMITS.review;if(!file||!/^image\/(jpeg|png|webp)$/i.test(file.type||''))return reject(new Error('Only JPG, PNG, or WebP images are supported.'));const reader=new FileReader();reader.onerror=()=>reject(reader.error||new Error('Could not read image'));reader.onload=()=>{const img=new Image();img.onerror=()=>reject(new Error('Invalid image'));img.onload=()=>{const scale=Math.min(1,cfg.maxEdge/Math.max(img.naturalWidth,img.naturalHeight));const w=Math.max(1,Math.round(img.naturalWidth*scale)),h=Math.max(1,Math.round(img.naturalHeight*scale));const canvas=document.createElement('canvas');canvas.width=w;canvas.height=h;const ctx=canvas.getContext('2d',{alpha:false});ctx.drawImage(img,0,0,w,h);const quality=cfg.quality;canvas.toBlob(blob=>{if(!blob)return reject(new Error('Image compression failed'));if(blob.size>cfg.maxBytes)return reject(new Error('Image remains too large after compression. Choose a smaller image.'));resolve({blob,width:w,height:h,sizeBytes:blob.size,mimeType:'image/jpeg'});},'image/jpeg',quality);};img.src=reader.result;};reader.readAsDataURL(file);});}
 async function upload(file,purpose,meta={}){const cfg=LIMITS[purpose]||LIMITS.review;const cooked=await resize(file,purpose==='vr360'?'vr360':purpose);const s=await client().auth.getSession();const uid=s.data.session?.user?.id;if(!uid)throw new Error('Sign in required to upload media.');const bucket=purpose==='vr360'?BUCKETS.location:BUCKETS[purpose];const scope=meta.businessId||meta.locationId||meta.reviewId||meta.postId||uid;const path=`${scope}/${uid}/${crypto.randomUUID()}.${ext()}`;const {error}=await client().storage.from(bucket).upload(path,cooked.blob,{contentType:cooked.mimeType,upsert:false,cacheControl:'31536000'});if(error)throw error;const {data}=client().storage.from(bucket).getPublicUrl(path);return {...cooked,bucket,path,url:data.publicUrl,mediaType:purpose==='vr360'?'vr360':purpose};}
 M.upload=upload;
 M.uploadAvatar=file=>upload(file,'avatar');
 M.uploadReviewPhoto=file=>upload(file,'review');
 M.uploadSocialPhoto=file=>upload(file,'social');
 M.uploadLocationPhoto=file=>upload(file,'location');
 M.uploadVr360=file=>upload(file,'vr360');
 M.recordLocationPhoto=async(media,locationId,userId,caption='',sortOrder=0)=>{const {data,error}=await client().from('location_photos').insert({location_id:locationId,user_id:userId,storage_path:media.path,caption,media_type:media.mediaType||'photo',mime_type:media.mimeType,size_bytes:media.sizeBytes,width:media.width,height:media.height,sort_order:sortOrder}).select().single();if(error)throw error;return data;};
 M.recordReviewPhoto=async(media,reviewId,sortOrder=0)=>{const {data,error}=await client().from('review_photos').insert({review_id:reviewId,storage_path:media.path,mime_type:media.mimeType,size_bytes:media.sizeBytes,width:media.width,height:media.height,sort_order:sortOrder}).select().single();if(error)throw error;return data;};
 M.createSocialPost=async({content='',locationId=null,media=null})=>{const s=await client().auth.getSession();const userId=s.data.session?.user?.id;if(!userId)throw new Error('Sign in required.');const row={user_id:userId,location_id:locationId,content,media_url:media?.url||null,media_type:media?.mediaType||null,media_storage_path:media?.path||null,media_size_bytes:media?.sizeBytes||null,media_width:media?.width||null,media_height:media?.height||null};const {data,error}=await client().from('social_posts').insert(row).select().single();if(error)throw error;return data;};
 M.prepareImage=resize;
})();