import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";
const OVERPASS="https://overpass-api.de/api/interpreter";
const SUPABASE_URL=Deno.env.get("SUPABASE_URL")!;
const SUPABASE_ANON_KEY=Deno.env.get("SUPABASE_ANON_KEY")!;
const SUPABASE_SERVICE_ROLE_KEY=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY");
const OBS_KEYS:Record<string,string>={"toilets:access":"toilet_access","toilets:fee":"toilet_fee","opening_hours":"opening_hours","toilets:opening_hours":"toilet_opening_hours","toilets:wheelchair":"wheelchair_accessible","wheelchair":"wheelchair_accessible","toilets:handwashing":"handwashing","toilets:soap":"soap","toilets:paper_supplied":"paper_supplied","toilets:hand-drying":"hand_drying","changing_table":"changing_table","toilets:changing_table":"changing_table","toilets:unisex":"unisex","toilets:gender_neutral":"gender_neutral","toilets:menstrual_products":"menstrual_products","toilets:disposal":"sanitary_disposal","toilets:shower":"shower","toilets:bidet":"bidet","toilets:position":"toilet_position","toilets:type":"toilet_type","toilets:number":"toilet_count","toilets:supervised":"supervised","toilets:drinking_water":"drinking_water","amenity":"osm_amenity","access":"access","fee":"fee","operator":"operator","brand":"brand"};
function placeType(t:Record<string,string>){if(t.amenity==='toilets')return'restroom';if(t.amenity==='fuel')return'gas_station';if(t.amenity==='fast_food')return'fast_food';if(t.amenity==='cafe')return'cafe';if(['restaurant','hospital','clinic','pharmacy','library','bank','atm'].includes(t.amenity||''))return t.amenity;if(t.shop)return'retail';if(t.leisure)return'park';if(t.tourism)return'lodging';return t.amenity||t.shop||t.leisure||t.tourism||'place'}
function normalize(el:any){const t=el.tags||{},lat=Number(el.lat??el.center?.lat),lng=Number(el.lon??el.center?.lon),obs:Record<string,string>={};for(const[k,v]of Object.entries(OBS_KEYS))if(t[k]!=null&&String(t[k]).trim()!=='')obs[v]=String(t[k]);return{source_id:`osm:${el.type}:${el.id}`,latitude:lat,longitude:lng,name:t.name||t.operator||(t.amenity==='toilets'?'Public Restroom':'Nearby Place'),place_type:placeType(t),address:[t['addr:housenumber'],t['addr:street']].filter(Boolean).join(' ')||t['addr:full']||'',city:t['addr:city']||'',state:t['addr:state']||'',postal_code:t['addr:postcode']||'',phone:t.phone||t['contact:phone']||'',website:t.website||t['contact:website']||'',osm_amenity:t.amenity||'',observations:obs,source_metadata:{osm_type:el.type,osm_id:String(el.id),tags:t}}}
function bbox(body:any){const b=body?.bbox;if(!Array.isArray(b)||b.length!==4)throw Error('bbox must be [south,west,north,east]');const n=b.map(Number);if(n.some(Number.isNaN)||n[0]<-90||n[2]>90||n[1]<-180||n[3]>180||n[0]>=n[2]||n[1]>=n[3])throw Error('invalid bbox');if((n[2]-n[0])*(n[3]-n[1])>4)throw Error('bbox too large; use geographic batches');return n.join(',')}
function json(body:any,status=200){return new Response(JSON.stringify(body),{status,headers:{'content-type':'application/json'}})}
Deno.serve(async(req)=>{try{if(req.method==='OPTIONS')return new Response(null,{status:204,headers:{'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'authorization, x-client-info, apikey, content-type','Access-Control-Allow-Methods':'POST,OPTIONS'}});if(req.method!=='POST')return json({error:'POST required'},405);if(!SUPABASE_SERVICE_ROLE_KEY)throw Error('Server ingestion authority is not configured');const apikey=req.headers.get('apikey')||'';const auth=(req.headers.get('Authorization')||'').replace(/^Bearer\s+/i,'').trim();if(apikey!==SUPABASE_ANON_KEY&&auth!==SUPABASE_ANON_KEY&&!auth) return json({error:'Supabase client authorization required'},401);const b=await req.json(),bb=bbox(b);const q=`[out:json][timeout:30];(nwr["amenity"~"^(toilets|restaurant|fast_food|cafe|fuel|hospital|clinic|pharmacy|library|bank|atm)$"](${bb});nwr["shop"~"^(supermarket|convenience|mall|bakery)$"](${bb});nwr["leisure"~"^(park|playground|sports_centre)$"](${bb});nwr["tourism"~"^(hotel|motel|hostel)$"](${bb}););out center tags;`;const r=await fetch(`${OVERPASS}?data=${encodeURIComponent(q)}`,{headers:{accept:'application/json','User-Agent':'KleenestApp/1.0 (+https://matthagersenior.github.io/KleenestApp/)'} });if(!r.ok)throw Error(`Overpass HTTP ${r.status}`);const j=await r.json(),rows=(Array.isArray(j.elements)?j.elements:[]).map(normalize).filter((x:any)=>Number.isFinite(x.latitude)&&Number.isFinite(x.longitude));const db=createClient(SUPABASE_URL,SUPABASE_SERVICE_ROLE_KEY);const batches:any[]=[];for(let i=0;i<rows.length;i+=500){const out=await db.rpc('ingest_osm_locations',{p_rows:rows.slice(i,i+500)});if(out.error)throw out.error;batches.push(out.data)}return json({source:'OpenStreetMap',bbox:bb,fetched:rows.length,persisted:rows.length,batches})}catch(e){return json({error:e instanceof Error?e.message:String(e)},400)}});
