import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";
const OVERPASS="https://overpass-api.de/api/interpreter";
const SUPABASE_URL=Deno.env.get("SUPABASE_URL")!;
const SUPABASE_ANON_KEY=Deno.env.get("SUPABASE_ANON_KEY")!;
const SUPABASE_SERVICE_ROLE_KEY=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
function placeType(t:Record<string,string>){if(t.amenity==='toilets'||t.toilets==='yes'||['yes','public','customers'].includes(t['toilets:access']||''))return'restroom';if(t.amenity==='fuel')return'gas_station';if(t.amenity==='fast_food')return'fast_food';if(t.amenity==='cafe')return'cafe';if(['restaurant','hospital','clinic','pharmacy','library','bank','atm'].includes(t.amenity||''))return t.amenity;if(t.shop)return'retail';if(t.leisure)return'park';if(t.tourism)return'lodging';return t.amenity||t.shop||t.leisure||t.tourism||'place'}
function normalize(el:any){const t=el.tags||{},lat=Number(el.lat??el.center?.lat),lng=Number(el.lon??el.center?.lon),ptype=placeType(t),observations:Record<string,string>={};for(const[k,v]of Object.entries(t))if(v!=null&&String(v).trim()!=='')observations[k]=String(v);const bathroom=ptype==='restroom';return{source_id:`osm:${el.type}:${el.id}`,latitude:lat,longitude:lng,name:t.name||t.operator||(t.amenity==='toilets'?'Public Restroom':bathroom?'Restroom at '+(t.name||t.operator||'Nearby Place'):'Nearby Place'),place_type:ptype,address:[t['addr:housenumber'],t['addr:street']].filter(Boolean).join(' ')||t['addr:full']||'',city:t['addr:city']||'',state:t['addr:state']||'',postal_code:t['addr:postcode']||'',phone:t.phone||t['contact:phone']||'',website:t.website||t['contact:website']||'',osm_amenity:t.amenity||'',observations,source_metadata:{osm_type:el.type,osm_id:String(el.id),tags:t,bathroom_confirmed:bathroom,bathroom_access:t.access||t['toilets:access']||null,bathroom_source:t.amenity==='toilets'?'dedicated_restroom':'host_feature'}}}
function bbox(body:any){const b=body?.bbox;if(!Array.isArray(b)||b.length!==4)throw Error('bbox must be [south,west,north,east]');const n=b.map(Number);if(n.some(Number.isNaN)||n[0]<-90||n[2]>90||n[1]<-180||n[3]>180||n[0]>=n[2]||n[1]>=n[3])throw Error('invalid bbox');if((n[2]-n[0])*(n[3]-n[1])>4)throw Error('bbox too large; use geographic batches');return n.join(',')}
const json=(x:any,s=200)=>new Response(JSON.stringify(x),{status:s,headers:{'content-type':'application/json','Access-Control-Allow-Origin':'*'}});
Deno.serve(async(req)=>{try{if(req.method==='OPTIONS')return new Response(null,{status:204,headers:{'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'authorization,apikey,content-type'}});if(req.method!=='POST')return json({error:'POST required'},405);const apikey=req.headers.get('apikey')||'';const auth=(req.headers.get('Authorization')||'').replace(/^Bearer\s+/i,'').trim();if(apikey!==SUPABASE_ANON_KEY&&auth!==SUPABASE_ANON_KEY&&!auth)return json({error:'Supabase client authorization required'},401);const body=await req.json(),bb=bbox(body),jobId=body.job_id||null;const q=`[out:json][timeout:45];(nwr["amenity"="toilets"](${bb});nwr["toilets"="yes"](${bb});nwr["toilets:access"~"^(yes|public|customers)$"](${bb}););out center tags;`;const db=createClient(SUPABASE_URL,SUPABASE_SERVICE_ROLE_KEY);if(jobId)await db.from('external_import_jobs').update({status:'running',started_at:new Date().toISOString(),error_detail:null}).eq('id',jobId);const r=await fetch(`${OVERPASS}?data=${encodeURIComponent(q)}`,{headers:{accept:'application/json','User-Agent':'KleenestApp/1.0 (+https://matthagersenior.github.io/KleenestApp/)'} });if(!r.ok)throw Error(`Overpass HTTP ${r.status}`);const j=await r.json(),rows=(Array.isArray(j.elements)?j.elements:[]).map(normalize).filter((x:any)=>Number.isFinite(x.latitude)&&Number.isFinite(x.longitude)&&x.place_type==='restroom');let imported=0,updated=0,observations=0;for(let i=0;i<rows.length;i+=500){const out=await db.rpc('ingest_osm_locations',{p_rows:rows.slice(i,i+500)});if(out.error)throw out.error;imported+=Number(out.data?.imported_locations||0);updated+=Number(out.data?.updated_locations||0);observations+=Number(out.data?.observations_upserted||0)}if(jobId)await db.from('external_import_jobs').update({status:'completed',finished_at:new Date().toISOString(),records_seen:rows.length,records_imported:imported,observations_imported:observations,error_detail:null}).eq('id',jobId);return json({ok:true,source:'OpenStreetMap',classification:'known_bathrooms',bbox:bb,fetched:rows.length,imported_locations:imported,updated_locations:updated,observations_upserted:observations})}catch(e){return json({ok:false,error:e instanceof Error?e.message:String(e)},400)}});
