/* Kleenest Maps Route Core — first-class routing capability inside Maps. */
const ROUTE_STATUSES=Object.freeze({DRAFT:'draft',ACTIVE:'active',COMPLETED:'completed',CANCELLED:'cancelled'});
const METRICS=Object.freeze({START:'route_started',STOP:'route_stop_completed',COMPLETE:'route_completed',SHARE:'route_shared',PREVIEW:'route_previewed'});
export function createMapsRoutes({supabase,progression=null,social=null,user=null,routing=null}={}){
 let activeRoute=null,selectedStops=[];const routingReady=routing?Promise.resolve(routing):import('./maps-routing.js').then(m=>m.createMapsRouting());
 const auth=()=>{if(!user?.id)throw new Error('Authentication is required for route actions.')};const emit=(metric,payload={})=>progression?.record?.({metric,source_type:'route',source_id:activeRoute?.id??null,payload});
 async function create({name='My Kleenest Route',startLat=null,startLng=null,endLat=null,endLng=null,distanceMiles=0,estimatedMinutes=0}={}){auth();const {data,error}=await supabase.rpc('create_route_plan',{p_name:name,p_start_lat:startLat,p_start_lng:startLng,p_end_lat:endLat,p_end_lng:endLng,p_distance_miles:distanceMiles,p_estimated_minutes:estimatedMinutes});if(error)throw error;activeRoute=data;selectedStops=[];return activeRoute}
 async function hydrate(route){auth();if(!route?.id)throw new Error('A route is required.');const {data,error}=await supabase.from('route_stops').select('*,locations(name,address,latitude,longitude,place_type,bathroom_verification_status)').eq('route_id',route.id).order('stop_order');if(error)throw error;activeRoute=route;selectedStops=data||[];return activeRoute}
 async function addLocation(locationId,meta={}){auth();if(!locationId)throw new Error('A location is required.');if(!activeRoute)await create();if(selectedStops.some(x=>String(x.location_id)===String(locationId)))return selectedStops;const {data,error}=await supabase.from('route_stops').insert({route_id:activeRoute.id,location_id:locationId,stop_order:selectedStops.length,points_value:meta.pointsValue??10}).select('*,locations(name,address,latitude,longitude,place_type,bathroom_verification_status)').single();if(error)throw error;selectedStops.push(data);await supabase.from('route_plans').update({stops_count:selectedStops.length}).eq('id',activeRoute.id).eq('user_id',user.id);return selectedStops}
 async function reorder(stops){
  auth();
  if(!activeRoute?.id)throw new Error('No route selected.');
  const ordered=Array.isArray(stops)?stops.filter(Boolean):[];
  const ids=new Set(ordered.map(s=>String(s.id)));
  if(ordered.length!==selectedStops.length||ids.size!==selectedStops.length||selectedStops.some(s=>!ids.has(String(s.id))))throw new Error('Route reorder must contain every existing stop exactly once.');
  for(const [i,s] of ordered.entries()){const {error}=await supabase.from('route_stops').update({stop_order:-(i+1)}).eq('id',s.id).eq('route_id',activeRoute.id);if(error)throw error}
  for(const [i,s] of ordered.entries()){const {error}=await supabase.from('route_stops').update({stop_order:i}).eq('id',s.id).eq('route_id',activeRoute.id);if(error)throw error}
  selectedStops=ordered.map((s,i)=>({...s,stop_order:i}));
  return selectedStops;
 }
 async function preview({origin=null,destination=null,stops=selectedStops}={}){const points=[origin,...stops.map(s=>({latitude:s.locations?.latitude??s.latitude,longitude:s.locations?.longitude??s.longitude})),destination].filter(Boolean);if(points.length<2)throw new Error('A route preview needs an origin and at least one destination.');const service=await routingReady;const result=await service.preview(points);await emit(METRICS.PREVIEW,{distance_meters:result.distanceMeters,duration_seconds:result.durationSeconds,stop_count:stops.length});return result}
 async function optimize({origin=null,destination=null}={}){auth();if(selectedStops.length<3)return selectedStops.slice();const service=await routingReady;const points=selectedStops.map(s=>({id:s.id,latitude:s.locations?.latitude??s.latitude,longitude:s.locations?.longitude??s.longitude}));const ordered=await service.optimize({origin,destination,stops:points});const byId=new Map(selectedStops.map(s=>[String(s.id),s]));return reorder(ordered.map(x=>byId.get(String(x.id))).filter(Boolean))}
 async function start(){auth();if(!activeRoute?.id)throw new Error('No route selected.');if(!selectedStops.length)throw new Error('Add at least one stop before starting a route.');const {data,error}=await supabase.from('route_plans').update({status:ROUTE_STATUSES.ACTIVE}).eq('id',activeRoute.id).eq('user_id',user.id).select('*').single();if(error)throw error;activeRoute=data;const ev=await supabase.from('route_events').insert({route_id:data.id,user_id:user.id,event_type:'started',points_awarded:0,metadata:{stop_count:selectedStops.length}});if(ev.error)throw ev.error;await emit(METRICS.START,{stop_count:selectedStops.length});return data}
 async function completeStop(stopId,payload={}){auth();if(!activeRoute?.id)throw new Error('No active route.');const stop=selectedStops.find(x=>String(x.id)===String(stopId));if(!stop)throw new Error('Route stop not found.');const {data,error}=await supabase.from('route_stops').update({checked_in_at:new Date().toISOString()}).eq('id',stopId).eq('route_id',activeRoute.id).select('*').single();if(error)throw error;const ev=await supabase.from('route_events').insert({route_id:activeRoute.id,user_id:user.id,event_type:'stop_completed',route_stop_id:stopId,points_awarded:data.points_value??0,metadata:payload});if(ev.error)throw ev.error;selectedStops=selectedStops.map(x=>String(x.id)===String(stopId)?{...x,...data}:x);await emit(METRICS.STOP,{stop_id:stopId,point_value:data.points_value??0});return data}
 async function complete(){auth();if(!activeRoute?.id)throw new Error('No active route.');const {data,error}=await supabase.rpc('complete_route',{p_route_id:activeRoute.id});if(error)throw error;activeRoute=data;await emit(METRICS.COMPLETE,{points_earned:data?.points_earned??0});return data}
 async function cancel(){auth();if(!activeRoute?.id)return null;const {data,error}=await supabase.from('route_plans').update({status:ROUTE_STATUSES.CANCELLED}).eq('id',activeRoute.id).eq('user_id',user.id).select('*').single();if(error)throw error;activeRoute=data;return data}
 async function share(payload={}){auth();if(!activeRoute?.id)throw new Error('No route selected.');const ev=await supabase.from('route_events').insert({route_id:activeRoute.id,user_id:user.id,event_type:'route_shared',points_awarded:0,metadata:payload});if(ev.error)throw ev.error;await emit(METRICS.SHARE,payload);return social?.shareRoute?.(activeRoute,payload)??{route:activeRoute,shared:true}}
 async function listMine({status=null}={}){auth();let q=supabase.from('route_plans').select('*,route_stops(*,locations(name,address,latitude,longitude,place_type,bathroom_verification_status))').eq('user_id',user.id).order('created_at',{ascending:false});if(status)q=q.eq('status',status);const {data,error}=await q;if(error)throw error;return data??[]}
 return Object.freeze({ROUTE_STATUSES,METRICS,create,hydrate,addLocation,reorder,preview,optimize,start,completeStop,complete,cancel,share,listMine,getActive:()=>activeRoute,getStops:()=>selectedStops.slice(),destroy:()=>{activeRoute=null;selectedStops=[]}})
}