/* Maps Route Core: first-class route capability inside Maps, backed by production schema/RPCs. */
const ROUTE_STATUSES=Object.freeze({DRAFT:'draft',ACTIVE:'active',COMPLETED:'completed',CANCELLED:'cancelled'});
const METRICS=Object.freeze({START:'route_started',STOP:'route_stop_completed',COMPLETE:'route_completed',SHARE:'route_shared'});
export function createMapsRoutes({supabase,progression=null,social=null,user=null}={}){let activeRoute=null,selectedStops=[];const auth=()=>{if(!user?.id)throw new Error('Authentication is required for route actions.')};const emit=(metric,payload={})=>progression?.record?.({metric,source_type:'route',source_id:activeRoute?.id??null,payload});
async function create({name='My Kleenest Route',startLat=null,startLng=null,endLat=null,endLng=null,distanceMiles=0,estimatedMinutes=0}={}){auth();const {data,error}=await supabase.rpc('create_route_plan',{p_name:name,p_start_lat:startLat,p_start_lng:startLng,p_end_lat:endLat,p_end_lng:endLng,p_distance_miles:distanceMiles,p_estimated_minutes:estimatedMinutes});if(error)throw error;activeRoute=data;selectedStops=[];return activeRoute}
async function hydrate(route){activeRoute=route;const {data,error}=await supabase.from('route_stops').select('*').eq('route_id',route.id).order('stop_order');if(error)throw error;selectedStops=data||[];return activeRoute}
async function addLocation(locationId,meta={}){auth();if(!activeRoute)await create();if(selectedStops.some(x=>String(x.location_id)===String(locationId)))return selectedStops;const {data,error}=await supabase.from('route_stops').insert({route_id:activeRoute.id,location_id:locationId,stop_order:selectedStops.length,points_value:meta.pointsValue??10}).select('*').single();if(error)throw error;selectedStops.push(data);return selectedStops}
async function reorder(stops){auth();if(!activeRoute?.id)throw new Error('No route selected.');const rows=stops.map((s,i)=>supabase.from('route_stops').update({stop_order:i}).eq('id',s.id).eq('route_id',activeRoute.id));await Promise.all(rows);selectedStops=stops.map((s,i)=>({...s,stop_order:i}));return selectedStops}
async function start(){auth();if(!activeRoute?.id)throw new Error('No route selected.');const {data,error}=await supabase.from('route_plans').update({status:ROUTE_STATUSES.ACTIVE}).eq('id',activeRoute.id).eq('user_id',user.id).select('*').single();if(error)throw error;activeRoute=data;const ev=await supabase.from('route_events').insert({route_id:data.id,user_id:user.id,event_type:'started',points_awarded:0,metadata:{}});if(ev.error)throw ev.error;await emit(METRICS.START);return data}
async function completeStop(stopId,payload={}){auth();if(!activeRoute?.id)throw new Error('No active route.');const {data,error}=await supabase.from('route_stops').update({checked_in_at:new Date().toISOString()}).eq('id',stopId).eq('route_id',activeRoute.id).select('*').single();if(error)throw error;const ev=await supabase.from('route_events').insert({route_id:activeRoute.id,user_id:user.id,event_type:'stop_completed',route_stop_id:stopId,points_awarded:data.points_value??0,metadata:payload});if(ev.error)throw ev.error;await emit(METRICS.STOP,{stop_id:stopId,point_value:data.points_value??0});return data}
async function complete(){auth();if(!activeRoute?.id)throw new Error('No active route.');const {data,error}=await supabase.rpc('complete_route',{p_route_id:activeRoute.id});if(error)throw error;activeRoute=data;await emit(METRICS.COMPLETE);return data}
async function cancel(){auth();if(!activeRoute?.id)return null;const {data,error}=await supabase.from('route_plans').update({status:ROUTE_STATUSES.CANCELLED}).eq('id',activeRoute.id).eq('user_id',user.id).select('*').single();if(error)throw error;activeRoute=data;return data}
async function share(payload={}){auth();if(!activeRoute?.id)throw new Error('No route selected.');const ev=await supabase.from('route_events').insert({route_id:activeRoute.id,user_id:user.id,event_type:'route_shared',points_awarded:0,metadata:payload});if(ev.error)throw ev.error;await emit(METRICS.SHARE,payload);return social?.shareRoute?.(activeRoute,payload)??{route:activeRoute,shared:true}}
async function listMine({status=null}={}){auth();let q=supabase.from('route_plans').select('*,route_stops(*)').eq('user_id',user.id).order('created_at',{ascending:false});if(status)q=q.eq('status',status);const {data,error}=await q;if(error)throw error;return data??[]}
return Object.freeze({ROUTE_STATUSES,METRICS,create,hydrate,addLocation,reorder,start,completeStop,complete,cancel,share,listMine,getActive:()=>activeRoute,getStops:()=>selectedStops.slice(),destroy:()=>{activeRoute=null;selectedStops=[]}})}